This is self-contained tutorial for pytorch and deep learning

# Datatypes

In [1]:
import torch

In [4]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.0459e-42, 0.0000e+00],
        [0.0000e+00, 1.9421e+20, 0.0000e+00]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.9469, 0.9735, 0.3205],
        [0.3221, 0.8627, 0.3598],
        [0.9778, 0.5388, 0.8568],
        [0.9448, 0.5659, 0.9829],
        [0.4520, 0.0676, 0.2074]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype = torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x,dtype = torch.float)
print(x)

tensor([[0.8998, 0.6988, 0.9410],
        [0.8619, 0.8047, 0.9540],
        [0.1874, 0.0677, 0.4179],
        [0.9798, 0.8014, 0.6977],
        [0.7987, 0.4869, 0.3767]])


In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [25]:
torch.Tensor(3,3)
torch.tensor([3,3])
torch.ones(3)
torch.zeros(3)
torch.eye(3)
torch.arange(1,10,1)
torch.linspace(1,10,10)
torch.rand(1,2)
torch.randn(2,2)
#torch.normal()
#torch.uniform(1,2)
torch.randperm(5)

tensor([2, 1, 0, 4, 3])

In [30]:
y = torch.randn(5,3)
print(x + y)
print(torch.add(x,y))
result = torch.empty(5,3)
torch.add(x,y,out = result)

x.add_(y)
#PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()

tensor([[-0.3815,  0.3631,  1.6018],
        [ 1.8685,  1.9909,  0.0468],
        [ 0.6946,  1.6934,  1.5964],
        [ 1.3171,  0.5261,  1.5544],
        [ 0.3374,  1.0947,  0.9672]])
tensor([[-0.3815,  0.3631,  1.6018],
        [ 1.8685,  1.9909,  0.0468],
        [ 0.6946,  1.6934,  1.5964],
        [ 1.3171,  0.5261,  1.5544],
        [ 0.3374,  1.0947,  0.9672]])


tensor([[-0.3815,  0.3631,  1.6018],
        [ 1.8685,  1.9909,  0.0468],
        [ 0.6946,  1.6934,  1.5964],
        [ 1.3171,  0.5261,  1.5544],
        [ 0.3374,  1.0947,  0.9672]])

In [31]:
#我们还可以使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。
y = x[0,:]
y += 1
print(y)

tensor([0.6185, 1.3631, 2.6018])


In [ ]:
y = x.view(15)
